const defaultOutOfScope = [
  'New wallet UX and non-ZK frontend polish',
  'Unrelated Soroban business logic outside the withdrawal proof boundary',
];

const areaBaseLabels = {
  foundations: ['circuits'],
  commitment: ['circuits'],
  merkle: ['circuits'],
  withdraw: ['circuits'],
  prover: ['circuits'],
  'sdk-zk': [],
  tooling: [],
  testing: ['testing'],
  security: ['security'],
  performance: ['optimization'],
};

const paths = {
  readme: 'README.md',
  labels: 'ops/github/labels.mjs',
  wave1: 'ops/github/waves/zk-wave-1.mjs',
  issueOps: 'scripts/github_issue_ops.mjs',
  zkTicketCheck: 'scripts/zk_ticket_check.mjs',
  rebuildZk: 'scripts/rebuild-zk.sh',
  refreshManifest: 'scripts/refresh_manifest.mjs',
  generateVectors: 'scripts/generate_commitment_vectors.mjs',
  sdkArtifacts: 'sdk/src/artifacts.ts',
  sdkEncoding: 'sdk/src/encoding.ts',
  sdkPublicInputs: 'sdk/src/public_inputs.ts',
  sdkPoseidon: 'sdk/src/poseidon.ts',
  sdkNote: 'sdk/src/note.ts',
  sdkMerkle: 'sdk/src/merkle.ts',
  sdkProof: 'sdk/src/proof.ts',
  sdkWithdraw: 'sdk/src/withdraw.ts',
  sdkWitness: 'sdk/src/witness.ts',
  sdkNoirBackend: 'sdk/src/backends/noir.ts',
  sdkTypes: 'sdk/src/index.ts',
  sdkTests: 'sdk/test/',
  frontendSdk: 'frontend/lib/sdk.ts',
  circuitWithdrawMain: 'circuits/withdraw/src/main.nr',
  circuitWithdrawSpend: 'circuits/withdraw/src/spend.nr',
  circuitConstants: 'circuits/lib/src/constants.nr',
  circuitNullifier: 'circuits/lib/src/hash/nullifier.nr',
  circuitDenomination: 'circuits/lib/src/validation/denomination.nr',
  circuitVectors: 'circuits/TEST_VECTORS.md',
  contractRs: 'contracts/privacy_pool/src/contract.rs',
  contractVerifier: 'contracts/privacy_pool/src/crypto/verifier.rs',
  contractMerkle: 'contracts/privacy_pool/src/crypto/merkle.rs',
  contractWithdraw: 'contracts/privacy_pool/src/core/withdraw.rs',
  contractView: 'contracts/privacy_pool/src/core/view.rs',
  contractState: 'contracts/privacy_pool/src/types/state.rs',
  contractErrors: 'contracts/privacy_pool/src/types/errors.rs',
  contractEvents: 'contracts/privacy_pool/src/types/events.rs',
  contractAnalytics: 'contracts/privacy_pool/src/storage/analytics.rs',
  contractAddressDecoder: 'contracts/privacy_pool/src/utils/address_decoder.rs',
  contractValidation: 'contracts/privacy_pool/src/utils/validation.rs',
  contractConfigStorage: 'contracts/privacy_pool/src/storage/config.rs',
  contractNullifierStorage: 'contracts/privacy_pool/src/storage/nullifier.rs',
  contractUnitTest: 'contracts/privacy_pool/src/test.rs',
  contractIntegrationTest: 'contracts/privacy_pool/src/integration_test.rs',
};

const refs = (...keys) => keys.map((key) => paths[key]);

function zkIssue({
  key,
  title,
  area,
  priority,
  complexity,
  summary,
  scope,
  acceptance,
  outOfScope = defaultOutOfScope,
  dependencies = [],
  references = [],
  codeAreas = references,
  labels = [],
}) {
  return {
    key,
    title,
    area,
    priority,
    complexity,
    summary,
    scope,
    acceptance,
    outOfScope,
    dependencies,
    references,
    codeAreas,
    labels: Array.from(new Set([...(areaBaseLabels[area] ?? []), ...labels])),
  };
}

const wave = {
  title: 'PrivacyLayer ZK Wave 2',
  defaultLabels: ['bounty', 'wave: zk-2'],
  issues: [
    // Contract and verifier parity (10)
    zkIssue({
      key: 'ZK-071',
      title: 'Split the withdrawal circuit schema from the contract verifier payload explicitly',
      area: 'withdraw',
      priority: 'High',
      complexity: 'High',
      summary:
        'The circuit now exposes eight public inputs while the Soroban verifier still behaves like it only sees six. Make the split between circuit-facing and contract-facing payloads explicit so witness generation and contract calls stop drifting.',
      scope: [
        'Define separate typed payloads for full circuit public inputs and the reduced contract verifier input set.',
        'Remove comments and helper names that imply one schema serves both boundaries unchanged.',
        'Add parity tests that prove the reduced contract payload is derived from the full circuit payload deterministically.',
      ],
      acceptance: [
        'SDK code, contract types, and tests use distinct names for full versus reduced public-input payloads.',
        'Schema order is pinned in one place per boundary and regression tested.',
        'No helper silently drops or reorders pool or denomination fields.',
      ],
      dependencies: ['ZK-032', 'ZK-045'],
      references: refs('circuitWithdrawMain', 'sdkEncoding', 'sdkPublicInputs', 'sdkProof', 'contractVerifier', 'contractState'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-072',
      title: 'Replace lossy recipient decoding with a verifiable address-binding strategy',
      area: 'withdraw',
      priority: 'High',
      complexity: 'High',
      summary:
        'The SDK currently hashes Stellar addresses into fields while the contract tries to decode a concrete address back out of 32 bytes. Replace that mismatch with a recipient-binding design the contract can actually verify.',
      scope: [
        'Choose a single recipient-binding model for the proof boundary, such as explicit recipient argument plus hashed public input binding.',
        'Update SDK encoding and contract withdraw flow together so the same address semantics are used end to end.',
        'Add negative tests for mismatched recipient argument versus proof-bound recipient commitment.',
      ],
      acceptance: [
        'The contract no longer attempts to reconstruct an address from an irreversible hash format.',
        'SDK witness generation and contract verification agree on recipient binding rules.',
        'Cross-stack tests show the wrong recipient is rejected deterministically.',
      ],
      dependencies: ['ZK-031'],
      references: refs('sdkEncoding', 'sdkPublicInputs', 'sdkProof', 'contractWithdraw', 'contractAddressDecoder', 'contractIntegrationTest'),
      labels: ['testing', 'security'],
    }),
    zkIssue({
      key: 'ZK-073',
      title: 'Redesign relayer binding and zero-relayer semantics across SDK and contract code',
      area: 'withdraw',
      priority: 'High',
      complexity: 'High',
      summary:
        'Recipient binding is not the only mismatch. Relayer handling still mixes zero-field sentinels, decoded addresses, and fee rules in ways that are easy to misapply across stacks.',
      scope: [
        'Define one relayer binding contract for no-relayer, relayer-with-fee, and malformed-relayer cases.',
        'Align SDK serialization, circuit validation, and Soroban withdraw handling around that contract.',
        'Cover fee zero, relayer zero, and relayer mismatch cases in end-to-end tests.',
      ],
      acceptance: [
        'Relayer handling no longer depends on ad hoc zero-address assumptions in multiple modules.',
        'The contract accepts only relayer encodings that the SDK can produce canonically.',
        'Regression tests distinguish absent relayer from malformed relayer cleanly.',
      ],
      dependencies: ['ZK-036', 'ZK-072'],
      references: refs('sdkEncoding', 'sdkProof', 'circuitWithdrawSpend', 'contractWithdraw', 'contractAddressDecoder', 'contractValidation'),
      labels: ['testing', 'security'],
    }),
    zkIssue({
      key: 'ZK-074',
      title: 'Attach circuit version and manifest identity to on-chain verifying keys',
      area: 'withdraw',
      priority: 'High',
      complexity: 'High',
      summary:
        'Pool-scoped verifying keys currently do not record which circuit artifact set, public-input arity, or manifest hash they correspond to. Tighten VK metadata so upgrades and rollbacks are auditable.',
      scope: [
        'Extend the on-chain verifying-key record with circuit identifier, public-input count, and manifest hash metadata.',
        'Validate that SDK proof payloads and contract VK metadata agree before attempting pairing verification.',
        'Document the expected upgrade path for circuit and VK changes across pools.',
      ],
      acceptance: [
        'Each stored VK is identifiable by pool, circuit build, and verifier shape.',
        'Mismatched proof payloads can fail before expensive pairing work begins.',
        'Integration tests cover VK mismatch and stale-VK scenarios.',
      ],
      dependencies: ['ZK-006', 'ZK-041'],
      references: refs('sdkArtifacts', 'sdkNoirBackend', 'contractVerifier', 'contractState', 'contractConfigStorage', 'contractIntegrationTest'),
      labels: ['security'],
    }),
    zkIssue({
      key: 'ZK-075',
      title: 'Add structural guards for proof, VK, and public-input shapes before BN254 parsing',
      area: 'withdraw',
      priority: 'High',
      complexity: 'Medium',
      summary:
        'The verifier path should reject malformed byte lengths, wrong IC counts, and impossible payload shapes before deserializing elliptic-curve points or touching pairing logic.',
      scope: [
        'Validate G1 and G2 byte lengths, IC vector length, and public-input arity on the Soroban side before cryptographic operations.',
        'Mirror the same invariants in the SDK formatting layer so malformed payloads fail early in both environments.',
        'Add a malformed payload corpus that proves the guards are stable.',
      ],
      acceptance: [
        'Malformed proof or VK structures fail with explicit pre-verification errors.',
        'Contract and SDK tests cover short, long, and count-mismatch payloads.',
        'Verifier code is no longer the first place malformed data is discovered.',
      ],
      dependencies: ['ZK-044'],
      references: refs('sdkWitness', 'sdkProof', 'contractVerifier', 'contractState', 'contractErrors', 'contractUnitTest'),
      labels: ['testing', 'security'],
    }),
    zkIssue({
      key: 'ZK-076',
      title: 'Generate contract withdraw fixtures from SDK serialization instead of hand-built inputs',
      area: 'withdraw',
      priority: 'Medium',
      complexity: 'High',
      summary:
        'Contract tests still lean heavily on synthetic field values and dummy payloads. Replace those with fixtures emitted from the same serialization path the SDK will use in production.',
      scope: [
        'Produce contract-consumable public-input fixtures from SDK witness and formatting helpers.',
        'Use generated fixtures in Soroban unit and integration tests instead of hand-authoring arbitrary field values.',
        'Track fixture provenance back to the artifact manifest and input schema version.',
      ],
      acceptance: [
        'At least one Soroban test path uses generated public-input fixtures rather than dummy values.',
        'Fixture generation is reproducible from local scripts.',
        'Contract fixture drift is caught by SDK-side regeneration checks.',
      ],
      dependencies: ['ZK-004', 'ZK-071'],
      references: refs('sdkProof', 'sdkWithdraw', 'contractUnitTest', 'contractIntegrationTest', 'refreshManifest', 'generateVectors'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-077',
      title: 'Remove duplicate `is_known_root` entrypoints and settle pool-scoped root lookup semantics',
      area: 'withdraw',
      priority: 'High',
      complexity: 'Medium',
      summary:
        'The contract ABI currently exposes two `is_known_root` functions with conflicting signatures, which breaks macro expansion and obscures whether root membership is global or pool-scoped.',
      scope: [
        'Collapse root lookup into one unambiguous contract API with pool-scoped semantics.',
        'Rename or remove helpers that still imply a global root history when state is pool-local.',
        'Update tests and docs to match the final ABI.',
      ],
      acceptance: [
        'The contract test build no longer fails on duplicate `is_known_root` symbols.',
        'View helpers, contract ABI, and tests agree on pool-scoped root lookup.',
        'No remaining public API suggests a root is valid outside its pool.',
      ],
      references: refs('contractRs', 'contractView', 'contractMerkle', 'contractUnitTest', 'contractIntegrationTest'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-078',
      title: 'Repair the broken contract ZK test suite and add a compile gate for it',
      area: 'testing',
      priority: 'High',
      complexity: 'Medium',
      summary:
        'The current Soroban test build is failing before meaningful verification work begins. Fix the broken test file state and then keep it from regressing silently.',
      scope: [
        'Repair the malformed integration-test file and any ABI fallout that prevents `cargo test` from compiling.',
        'Add a dedicated contract test gate to the ticket checker for issues that touch verifier or withdraw code.',
        'Capture the minimum green contract test surface needed for ZK changes.',
      ],
      acceptance: [
        '`cargo test` in `contracts/` is runnable again for ZK-related changes.',
        'Contract-relevant tickets derive Soroban validation commands automatically.',
        'Broken test file structure is caught before more ZK issues pile on top of it.',
      ],
      references: refs('contractRs', 'contractIntegrationTest', 'contractUnitTest', 'zkTicketCheck'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-079',
      title: 'Bind pool identity and denomination semantics at the contract withdraw boundary',
      area: 'withdraw',
      priority: 'High',
      complexity: 'High',
      summary:
        'The circuit and SDK now carry pool and denomination semantics, but the contract withdraw interface still receives a reduced payload that can drift from the pool configuration if not checked deliberately.',
      scope: [
        'Define which parts of pool identity and denomination are proven in-circuit and which are rechecked from on-chain pool configuration.',
        'Add contract-side assertions that reject payloads inconsistent with the target pool configuration.',
        'Cover mismatched pool and denomination scenarios in Soroban integration tests.',
      ],
      acceptance: [
        'Withdraw flow rejects inputs that are valid structurally but inconsistent with the selected pool config.',
        'Tests prove cross-pool or wrong-denomination payload reuse fails reliably.',
        'The contract boundary documents what it trusts from the proof versus from storage.',
      ],
      dependencies: ['ZK-029', 'ZK-030', 'ZK-071'],
      references: refs('circuitWithdrawMain', 'sdkPublicInputs', 'contractWithdraw', 'contractState', 'contractValidation', 'contractIntegrationTest'),
      labels: ['testing', 'security'],
    }),
    zkIssue({
      key: 'ZK-080',
      title: 'Add an end-to-end Soroban withdrawal harness driven by generated proof artifacts',
      area: 'withdraw',
      priority: 'Medium',
      complexity: 'High',
      summary:
        'The repo still lacks a contract-facing harness that exercises the full path from generated witness material through contract-shaped proof and public-input payloads. Add one before the first real proving flow lands.',
      scope: [
        'Build a harness that consumes generated artifacts and serialized public inputs instead of ad hoc byte blobs.',
        'Exercise at least one happy-path and one failure-path withdraw call against the contract boundary.',
        'Keep the harness isolated enough to run in CI once real proving assets are available.',
      ],
      acceptance: [
        'A single test path demonstrates how generated ZK material reaches the Soroban withdraw entrypoint.',
        'The harness can be wired to mock or real proof backends without changing contract-facing serialization.',
        'Failure output distinguishes proof failure, root failure, and nullifier failure.',
      ],
      dependencies: ['ZK-050', 'ZK-076'],
      references: refs('sdkWithdraw', 'sdkNoirBackend', 'contractWithdraw', 'contractIntegrationTest', 'rebuildZk'),
      labels: ['testing'],
    }),

    // SDK schema and artifact cleanup (10)
    zkIssue({
      key: 'ZK-081',
      title: 'Consolidate `sdk/src/encoding.ts` and `sdk/src/public_inputs.ts` into one canonical layer',
      area: 'sdk-zk',
      priority: 'High',
      complexity: 'High',
      summary:
        'The SDK currently has two overlapping encoding modules with conflicting public-input counts, nullifier semantics, and helper behavior. Collapse them before more callers hard-code the wrong contract.',
      scope: [
        'Choose one canonical home for field, address, and public-input serialization logic.',
        'Delete or thin the duplicate module so future changes cannot land in only one place.',
        'Port all tests to the canonical exports and add a guard against duplicate schema definitions.',
      ],
      acceptance: [
        'There is one source of truth for withdrawal public-input ordering and field encoding.',
        'Tests no longer rely on parallel modules that disagree about schema length or semantics.',
        'Future schema edits require touching one primary SDK module.',
      ],
      dependencies: ['ZK-008', 'ZK-071'],
      references: refs('sdkEncoding', 'sdkPublicInputs', 'sdkProof', 'sdkWithdraw', 'sdkTests'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-082',
      title: 'Normalize numeric witness fields to canonical field hex across the SDK',
      area: 'sdk-zk',
      priority: 'High',
      complexity: 'Medium',
      summary:
        'Prepared witnesses still mix canonical field hex with raw decimal strings for amount-like values. Normalize them so witness validation, formatting, and caching all see one stable representation.',
      scope: [
        'Choose a single representation for amount, fee, and denomination in prepared witnesses and public-input helpers.',
        'Update proof formatting, cache keys, and tests to use the same representation consistently.',
        'Reject callers that still pass decimal strings where canonical field encodings are required.',
      ],
      acceptance: [
        'Prepared witness fields do not mix decimal and field-hex encodings for similar values.',
        'Zero values serialize canonically and round-trip through formatting helpers.',
        'Cache keys remain stable after normalization and are pinned by tests.',
      ],
      dependencies: ['ZK-007', 'ZK-081'],
      references: refs('sdkEncoding', 'sdkPublicInputs', 'sdkProof', 'sdkWithdraw', 'sdkWitness'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-083',
      title: 'Add a typed Poseidon2 integration boundary for the SDK',
      area: 'sdk-zk',
      priority: 'High',
      complexity: 'Medium',
      summary:
        'The current Poseidon2 dependency path is not typed cleanly enough for the TypeScript test build. Wrap the dependency behind a local typed boundary so the ZK SDK compiles reproducibly.',
      scope: [
        'Add local type declarations or a wrapper module for the Poseidon2 dependency used by commitment hashing.',
        'Ensure Jest and TypeScript builds resolve the dependency path consistently.',
        'Document the expected runtime surface so browser and Node backends do not guess at shapes.',
      ],
      acceptance: [
        'SDK tests no longer fail immediately on missing Poseidon2 module typing.',
        'Poseidon integration is imported through one typed module boundary.',
        'Build behavior is the same in test and production TypeScript compilation.',
      ],
      dependencies: ['ZK-009'],
      references: refs('sdkPoseidon', 'sdkNote', 'sdkTests', 'sdkTypes'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-084',
      title: 'Implement `loadNoirArtifacts()` for Node with manifest and VK validation',
      area: 'prover',
      priority: 'High',
      complexity: 'Medium',
      summary:
        'The Node artifact loader remains unimplemented even though the SDK now has versioned artifact path helpers and manifest logic. Finish the loader so consumers can actually use local artifacts safely.',
      scope: [
        'Load circuit JSON, ABI, and verifying-key material from the versioned artifact layout.',
        'Validate artifact hashes and names against the manifest before returning them.',
        'Surface stable loader errors for missing files, hash mismatch, and bad manifest shape.',
      ],
      acceptance: [
        'Node consumers can load artifacts by circuit name without hard-coded file plumbing.',
        'Manifest mismatches fail before proof generation starts.',
        'Loader behavior is covered by focused SDK tests.',
      ],
      dependencies: ['ZK-041', 'ZK-046'],
      references: refs('sdkArtifacts', 'sdkNoirBackend', 'refreshManifest', 'rebuildZk'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-085',
      title: 'Add a browser artifact loader with versioned URL and checksum support',
      area: 'prover',
      priority: 'Medium',
      complexity: 'High',
      summary:
        'The SDK needs a browser artifact-loading story that is as explicit about versions and integrity as the Node path, especially once proving assets move into the frontend.',
      scope: [
        'Define how browser callers locate versioned circuit artifacts, manifest files, and proving assets.',
        'Validate fetched artifacts against manifest hashes before exposing them to the proving backend.',
        'Keep the browser loader separate from filesystem-specific Node code.',
      ],
      acceptance: [
        'Browser callers can load versioned artifact bundles without reimplementing path logic.',
        'Checksum failure is surfaced as a stable loader error.',
        'No browser consumer needs to know the raw on-disk repo layout.',
      ],
      dependencies: ['ZK-048', 'ZK-084'],
      references: refs('sdkArtifacts', 'sdkNoirBackend', 'sdkWithdraw', 'refreshManifest', 'frontendSdk'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-086',
      title: 'Repair the versioned rebuild pipeline so outputs actually land in the declared layout',
      area: 'tooling',
      priority: 'High',
      complexity: 'Medium',
      summary:
        'The rebuild script declares a versioned artifact tree but still copies compiled circuit JSON into the old unversioned directory. Align the implementation with the layout contract before downstream loaders depend on the wrong path.',
      scope: [
        'Fix `scripts/rebuild-zk.sh` to emit circuit artifacts, manifests, and fixtures into the versioned directories it creates.',
        'Remove stale copies or duplicated write paths that keep old layouts half-alive.',
        'Add a check that fails if expected outputs are missing from the versioned tree after a rebuild.',
      ],
      acceptance: [
        'A clean rebuild produces artifacts only in the versioned layout or through clearly intentional compatibility links.',
        '`sdk/src/artifacts.ts` matches the actual rebuild output paths.',
        'Regression tests or checks catch future path drift immediately.',
      ],
      dependencies: ['ZK-041', 'ZK-047'],
      references: refs('sdkArtifacts', 'rebuildZk', 'refreshManifest'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-087',
      title: 'Emit a machine-readable verifier schema artifact for Rust and TypeScript parity tests',
      area: 'tooling',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'The verifier boundary currently lives partly in comments, partly in Rust structs, and partly in TypeScript arrays. Generate a machine-readable schema artifact that both stacks can test against.',
      scope: [
        'Define a schema artifact that records public-input names, order, byte widths, and contract-visible subset mappings.',
        'Generate that artifact during ZK rebuilds and make both SDK and contract tests consume it.',
        'Keep the artifact small enough to inspect in reviews while still being authoritative.',
      ],
      acceptance: [
        'Rust and TypeScript parity tests read the same verifier schema artifact.',
        'Schema drift no longer hides in comments or duplicated arrays.',
        'Rebuild output includes the verifier schema alongside circuit artifacts.',
      ],
      dependencies: ['ZK-071', 'ZK-086'],
      references: refs('sdkArtifacts', 'sdkEncoding', 'sdkPublicInputs', 'contractVerifier', 'contractState', 'rebuildZk'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-088',
      title: 'Version the public-input schema independently from the circuit artifact version',
      area: 'tooling',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'One artifact version number is not enough once the project needs to distinguish schema-only changes from full circuit rebuilds. Track public-input schema compatibility explicitly.',
      scope: [
        'Introduce a public-input schema version in manifests or adjacent metadata.',
        'Teach SDK loaders and proof formatters to reject incompatible schema versions explicitly.',
        'Document when a schema-only bump versus a full artifact bump is required.',
      ],
      acceptance: [
        'Schema compatibility is machine-readable instead of implied by directory names alone.',
        'SDK code fails fast on unsupported schema versions.',
        'Reviewers can tell whether a change altered the verifier boundary or only rebuild metadata.',
      ],
      dependencies: ['ZK-006', 'ZK-087'],
      references: refs('sdkArtifacts', 'sdkNoirBackend', 'refreshManifest', 'contractState'),
    }),
    zkIssue({
      key: 'ZK-089',
      title: 'Add ABI drift checks between compiled Noir artifacts and SDK witness builders',
      area: 'tooling',
      priority: 'High',
      complexity: 'Medium',
      summary:
        'The SDK can still drift from the compiled circuit ABI even when local tests look healthy. Add a machine check that compares compiled artifact ABI to the witness shape and field order the SDK emits.',
      scope: [
        'Load compiled artifact ABI and compare it against the SDK prepared-witness schema automatically.',
        'Fail on renamed fields, reordered arrays, or public/private split changes.',
        'Make the drift check part of the standard rebuild or CI path.',
      ],
      acceptance: [
        'Witness schema drift is detected without relying on manual review.',
        'ABI checks point to the exact field mismatch when they fail.',
        'The check runs against compiled artifacts rather than static assumptions.',
      ],
      dependencies: ['ZK-007', 'ZK-084'],
      references: refs('sdkProof', 'sdkNoirBackend', 'circuitWithdrawMain', 'rebuildZk'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-090',
      title: 'Route all generated artifact consumption through `sdk/src/artifacts.ts`',
      area: 'tooling',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'Path helpers exist, but artifact-consuming code can still fall back to ad hoc strings and comments. Enforce one artifact path layer so future layout changes are survivable.',
      scope: [
        'Audit artifact loads and references across SDK and scripts for raw path literals.',
        'Replace direct path assumptions with helpers from `sdk/src/artifacts.ts` or a shared utility layer.',
        'Add regression coverage for expected artifact paths by circuit and version.',
      ],
      acceptance: [
        'Artifact consumers do not hard-code repo layout fragments outside the shared path helper layer.',
        'Version bumps require changing one path abstraction rather than scattered string literals.',
        'Tests pin the key path derivations used by loaders and rebuild scripts.',
      ],
      dependencies: ['ZK-041', 'ZK-086'],
      references: refs('sdkArtifacts', 'sdkNoirBackend', 'rebuildZk', 'refreshManifest'),
      labels: ['testing'],
    }),

    // Runtime and proving backend productionization (10)
    zkIssue({
      key: 'ZK-091',
      title: 'Promote the Noir backend from interface wrapper to runnable Node proving backend',
      area: 'prover',
      priority: 'High',
      complexity: 'High',
      summary:
        'The backend wrapper can validate manifests but still cannot stand up a working proving engine without external glue. Finish the Node proving path so the SDK can generate real proofs locally.',
      scope: [
        'Integrate backend initialization with the actual Noir proving runtime used by the project.',
        'Hide backend-specific startup details behind the existing proving interface.',
        'Add smoke tests that use real artifacts and a minimal happy-path witness.',
      ],
      acceptance: [
        'Node callers can create a backend and attempt real proof generation with local artifacts.',
        'Backend initialization errors are distinct from witness and formatting errors.',
        'The proving path is exercised by at least one automated integration test.',
      ],
      dependencies: ['ZK-043', 'ZK-084'],
      references: refs('sdkNoirBackend', 'sdkProof', 'sdkWithdraw', 'sdkTests'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-092',
      title: 'Add a browser worker proving backend with cancellation and progress hooks',
      area: 'prover',
      priority: 'Medium',
      complexity: 'High',
      summary:
        'A browser backend needs more than environment selection. It needs worker isolation, cancellation, and progress surfaces so proof generation does not freeze the UI or deadlock integrations.',
      scope: [
        'Define a worker-safe proving backend boundary for browser runtimes.',
        'Support cancellation or teardown semantics for long-running proof jobs.',
        'Expose coarse progress or lifecycle events without leaking witness material.',
      ],
      acceptance: [
        'Proof generation can run off the main thread in browser integrations.',
        'Consumers can abort a proof job without leaking backend state.',
        'The browser backend reuses the same witness and formatting layers as Node.',
      ],
      dependencies: ['ZK-048', 'ZK-085'],
      references: refs('sdkNoirBackend', 'sdkWithdraw', 'sdkProof', 'frontendSdk'),
      labels: ['performance'],
    }),
    zkIssue({
      key: 'ZK-093',
      title: 'Split proof formatting into typed Soroban `Proof` bytes and verifier-input payloads',
      area: 'prover',
      priority: 'High',
      complexity: 'Medium',
      summary:
        'The SDK currently treats the raw proof bytes as almost the whole story. Separate typed contract proof formatting from public-input serialization so downstream integrations stop guessing at payload layout.',
      scope: [
        'Add explicit helpers for Soroban `Proof` struct encoding and reduced contract verifier payload encoding.',
        'Keep circuit-facing public-input formatting available separately from contract-facing formatting.',
        'Add contract-parity tests for each serialized component.',
      ],
      acceptance: [
        'Contract proof bytes and contract public-input bytes have dedicated typed helpers.',
        'No caller has to infer Soroban struct layout from raw byte arrays.',
        'Formatting helpers are covered by parity tests against Rust expectations.',
      ],
      dependencies: ['ZK-044', 'ZK-071'],
      references: refs('sdkProof', 'sdkWithdraw', 'contractState', 'contractVerifier', 'sdkTests'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-094',
      title: 'Separate backend instance caching from proof-result caching',
      area: 'prover',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'Proof caching already exists conceptually, but warm backend state and compiled proving context are a different optimization problem. Model them separately so reuse is predictable and testable.',
      scope: [
        'Introduce a cache or lifecycle layer for initialized proving backends distinct from proof-result caches.',
        'Avoid coupling backend instance reuse to witness-derived proof cache keys.',
        'Benchmark cold versus warm backend behavior with the new separation.',
      ],
      acceptance: [
        'Backend reuse is possible without pretending it is the same as proof reuse.',
        'Proof cache behavior remains deterministic after backend caching is added.',
        'Cold-start and warm-start metrics are visible in tests or benchmarks.',
      ],
      dependencies: ['ZK-057', 'ZK-091'],
      references: refs('sdkNoirBackend', 'sdkProof', 'sdkWithdraw', 'sdkTests'),
      labels: ['performance'],
    }),
    zkIssue({
      key: 'ZK-095',
      title: 'Add deterministic repeated-proof smoke tests for the real backend',
      area: 'prover',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'Once a real backend is wired in, repeated runs with the same artifacts and witness should at least satisfy stable verification and expected payload shape. Add smoke tests that capture that behavior.',
      scope: [
        'Run the same witness through the real backend multiple times and capture what is expected to remain stable.',
        'Verify each output off-chain or against the contract formatting layer.',
        'Document any intentional backend nondeterminism so caches and fixtures are designed correctly.',
      ],
      acceptance: [
        'Repeated proof runs are tested rather than assumed.',
        'Tests assert stable verification behavior even if byte-for-byte proof determinism is not guaranteed.',
        'Proof caching assumptions are backed by data from the actual backend.',
      ],
      dependencies: ['ZK-091'],
      references: refs('sdkNoirBackend', 'sdkWithdraw', 'sdkTests'),
      labels: ['testing', 'performance'],
    }),
    zkIssue({
      key: 'ZK-096',
      title: 'Add runtime capability negotiation and unsupported-runtime diagnostics',
      area: 'prover',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'Consumers need to know whether the runtime can prove, verify, or only format witnesses before they start a ZK flow. Make capability detection explicit instead of letting deep runtime failures answer that question.',
      scope: [
        'Define a capability model for Node, browser, worker, and witness-only environments.',
        'Surface stable unsupported-runtime errors before backend initialization or proving starts.',
        'Expose capability checks through a small SDK API that integrations can query.',
      ],
      acceptance: [
        'Integrations can tell whether proof generation is supported before invoking it.',
        'Unsupported environments fail with actionable errors instead of deep stack traces.',
        'Capability detection is covered by tests for common runtime modes.',
      ],
      dependencies: ['ZK-048', 'ZK-091'],
      references: refs('sdkNoirBackend', 'sdkNote', 'sdkWithdraw', 'sdkTypes'),
    }),
    zkIssue({
      key: 'ZK-097',
      title: 'Add a redacted witness-debug mode for proving failures',
      area: 'prover',
      priority: 'Low',
      complexity: 'Medium',
      summary:
        'Backend failures are difficult to debug, but dumping raw witnesses would be reckless. Add a debug mode that preserves structural insight while redacting note material and other sensitive fields.',
      scope: [
        'Define what witness metadata may be logged safely during local proving failures.',
        'Add a debug serializer that redacts secrets while preserving field names, lengths, and selected hashes.',
        'Make the feature opt-in and unavailable in production-by-default paths.',
      ],
      acceptance: [
        'Local developers can inspect proving failures without exposing raw note material.',
        'Sensitive fields are consistently redacted by one shared helper.',
        'Tests verify that debug output never contains note secrets or backup strings.',
      ],
      dependencies: ['ZK-049'],
      references: refs('sdkProof', 'sdkWithdraw', 'sdkWitness', 'sdkTests'),
      labels: ['security'],
    }),
    zkIssue({
      key: 'ZK-098',
      title: 'Add a manifest-aware off-chain verification helper that rejects schema mismatch first',
      area: 'prover',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'Off-chain verification is more useful when it can explain whether failure comes from proof invalidity or from artifact/schema mismatch. Build a helper that checks provenance before it verifies cryptography.',
      scope: [
        'Load verification artifacts together with manifest and schema metadata.',
        'Reject mismatched proof payloads or public-input schemas before invoking the verifying backend.',
        'Expose failure categories that distinguish bad proof, bad artifact set, and bad input schema.',
      ],
      acceptance: [
        'Off-chain verification can fail fast on mismatched artifact or schema versions.',
        'Verification callers receive stable error categories for common failure modes.',
        'Tests cover both successful verification and pre-verification mismatch cases.',
      ],
      dependencies: ['ZK-050', 'ZK-088'],
      references: refs('sdkNoirBackend', 'sdkWithdraw', 'sdkArtifacts', 'sdkTests'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-099',
      title: 'Add Soroban point and VK parser helpers for proof and verifier payload review',
      area: 'prover',
      priority: 'Low',
      complexity: 'Medium',
      summary:
        'It is currently too easy to treat proof and VK blobs as opaque byte arrays. Add parser helpers that can split or inspect contract-shaped G1 and G2 payloads safely in tests and tooling.',
      scope: [
        'Define typed helpers for `Proof` parts and verifying-key component layout used by Soroban.',
        'Use them in tests and local tooling that currently slices byte arrays manually.',
        'Keep the helpers review-oriented and validation-focused rather than turning them into a second verifier.',
      ],
      acceptance: [
        'Tests and scripts can inspect proof and VK payload structure without open-coded byte slicing.',
        'Parser helpers validate expected lengths and segment counts.',
        'Reviewing payload layout changes becomes easier and less error-prone.',
      ],
      dependencies: ['ZK-044', 'ZK-075'],
      references: refs('sdkProof', 'contractState', 'contractVerifier', 'sdkTests'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-100',
      title: 'Benchmark backend startup separately from proving throughput and cache warmth',
      area: 'performance',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'Current performance work is too coarse for operational decisions. Measure backend startup, first-proof latency, and warmed proof latency independently so optimization work can target the actual bottleneck.',
      scope: [
        'Instrument backend initialization time, first proof generation time, and warmed-run time separately.',
        'Compare Node and browser-oriented runtimes where available.',
        'Persist or snapshot the results in a lightweight benchmark format suitable for regression review.',
      ],
      acceptance: [
        'Benchmark output separates startup cost from per-proof cost.',
        'Performance regressions can be tied to backend initialization versus steady-state proving.',
        'Benchmark tooling reuses the real backend integration path rather than a mock.',
      ],
      dependencies: ['ZK-070', 'ZK-091', 'ZK-094'],
      references: refs('sdkNoirBackend', 'sdkWithdraw', 'sdkTests'),
      labels: ['testing'],
    }),

    // Live failures and correctness cleanup (10)
    zkIssue({
      key: 'ZK-101',
      title: 'Fix duplicate imports and file corruption in `sdk/test/witness_mutation.test.ts`',
      area: 'testing',
      priority: 'High',
      complexity: 'Trivial',
      summary:
        'The SDK test run currently trips on duplicated imports and conflicting declarations inside `witness_mutation.test.ts`. Clean up the file and add a guard so this kind of corruption fails fast.',
      scope: [
        'Remove duplicate import blocks and normalize the test file structure.',
        'Add a lint or lightweight check that catches duplicate test headers or declarations.',
        'Verify the repaired file still covers the intended witness mutation cases.',
      ],
      acceptance: [
        'The test file compiles cleanly under Jest and TypeScript.',
        'Mutation coverage remains intact after the cleanup.',
        'A simple guard exists to catch future duplicate-import accidents.',
      ],
      references: refs('sdkTests'),
    }),
    zkIssue({
      key: 'ZK-102',
      title: 'Resolve the buffer endianness expectation drift in public-input helper tests',
      area: 'testing',
      priority: 'Medium',
      complexity: 'Trivial',
      summary:
        'At least one public-input helper test currently expects the wrong numeric value for a byte buffer. Decide the intended endianness contract and make helpers, docs, and tests agree.',
      scope: [
        'Confirm the intended big-endian interpretation for field and byte conversion helpers.',
        'Fix whichever side is wrong: implementation, tests, or comments.',
        'Add a small table-driven test set for common byte-order edge cases.',
      ],
      acceptance: [
        'Byte-to-field conversion semantics are pinned by clear tests.',
        'There is no ambiguity about endianness in helper docs or comments.',
        'Related conversion helpers are reviewed for the same class of drift.',
      ],
      references: refs('sdkEncoding', 'sdkPublicInputs', 'sdkTests'),
    }),
    zkIssue({
      key: 'ZK-103',
      title: 'Canonicalize zero-valued field serialization throughout witness and public-input packing',
      area: 'testing',
      priority: 'High',
      complexity: 'Medium',
      summary:
        'Several code paths still serialize zero values as bare decimal strings or otherwise inconsistent formats. Standardize zero handling so padding bugs do not hide in optional fields and fees.',
      scope: [
        'Audit all zero-valued amount, fee, relayer, and pool-related serialization paths.',
        'Normalize them to the chosen canonical field representation end to end.',
        'Add regression tests for zero, max fee zero, and absent-relayer cases.',
      ],
      acceptance: [
        'Zero values round-trip through formatting helpers without representation drift.',
        'Tests cover both witness construction and packed public-input serialization.',
        'There is no remaining mix of `"0"` and 64-hex-zero encodings for the same contract field.',
      ],
      dependencies: ['ZK-082'],
      references: refs('sdkEncoding', 'sdkPublicInputs', 'sdkProof', 'sdkWithdraw', 'sdkTests'),
    }),
    zkIssue({
      key: 'ZK-104',
      title: 'Decide and document zero-account semantics for address validation paths',
      area: 'testing',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'Tests and helpers disagree on whether the all-A Stellar account sentinel should be treated as a valid public key, a special no-relayer alias, or rejected entirely. Decide that contract and pin it everywhere.',
      scope: [
        'Define the status of the zero-account sentinel in SDK address validation and relayer handling.',
        'Update tests, helper names, and constants to reflect that decision unambiguously.',
        'Ensure the chosen semantics are compatible with contract-side relayer logic.',
      ],
      acceptance: [
        'Address validation tests no longer contradict relayer sentinel handling.',
        'The zero-account semantics are documented in code close to the validator.',
        'SDK and contract optional-relayer paths agree on the sentinel policy.',
      ],
      references: refs('sdkEncoding', 'sdkPublicInputs', 'sdkProof', 'contractAddressDecoder', 'contractValidation', 'sdkTests'),
    }),
    zkIssue({
      key: 'ZK-105',
      title: 'Reconcile Merkle fixture generation with canonical field-range validation',
      area: 'testing',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'Generated Merkle vectors can currently produce roots that fail SDK canonical-field validation. Decide whether fixtures, validators, or conversion layers are wrong and make them consistent.',
      scope: [
        'Inspect fixture-generation assumptions for roots and siblings against the canonical field contract.',
        'Update either vector generation or validation rules so cross-stack fixtures represent reachable states.',
        'Add regression coverage for the exact failing vector class.',
      ],
      acceptance: [
        'Shared Merkle vectors no longer fail immediately on canonical-field checks unless intentionally negative.',
        'Fixture generators document how 32-byte nodes cross the field boundary.',
        'Tests isolate whether a vector is invalid structurally or only out of field range.',
      ],
      references: refs('sdkMerkle', 'sdkTests', 'circuitVectors'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-106',
      title: 'Introduce explicit mock-hash versus live-hash modes in SDK ZK helpers',
      area: 'testing',
      priority: 'High',
      complexity: 'High',
      summary:
        'Some SDK helpers still use SHA-256 structural stand-ins while newer paths use Poseidon2. Make the distinction explicit so tests cannot silently mix mock and live hash semantics.',
      scope: [
        'Define clear mock-hash and live-hash modes or abstractions for note, nullifier, and public-input helpers.',
        'Ensure fixtures and tests declare which mode they are using.',
        'Prevent production proof paths from accidentally using structural stand-ins.',
      ],
      acceptance: [
        'Hash mode is explicit in tests and proof helpers.',
        'Production proof generation cannot run on mock-hash configuration by accident.',
        'Existing tests are partitioned or updated so mixed-mode assumptions are visible.',
      ],
      dependencies: ['ZK-009', 'ZK-017'],
      references: refs('sdkPoseidon', 'sdkEncoding', 'sdkPublicInputs', 'sdkProof', 'sdkTests'),
      labels: ['security'],
    }),
    zkIssue({
      key: 'ZK-107',
      title: 'Add dependency-resolution smoke tests for the ZK SDK entrypoints',
      area: 'testing',
      priority: 'Medium',
      complexity: 'Trivial',
      summary:
        'The current Jest run fans out into many failures after a basic dependency-resolution problem. Add a shallow smoke check that proves key ZK modules load before full test execution.',
      scope: [
        'Create a lightweight test or build step that imports the main ZK entrypoints and fails fast on missing runtime or type dependencies.',
        'Run it before the broader Jest matrix to shorten failure loops.',
        'Include the Poseidon path and any runtime-specific backend entrypoints in the smoke surface.',
      ],
      acceptance: [
        'Missing dependency wiring fails in a small targeted check before dozens of suites explode.',
        'The smoke surface covers the modules most likely to break basic ZK imports.',
        'CI output becomes more diagnostic for broken dependency state.',
      ],
      references: refs('sdkTypes', 'sdkPoseidon', 'sdkNoirBackend', 'sdkTests'),
    }),
    zkIssue({
      key: 'ZK-108',
      title: 'Fail CI when multiple modules export competing withdrawal schema orders',
      area: 'testing',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'Wave 2 already exposed that the repo can carry more than one notion of withdrawal input order at once. Add a dedicated consistency test that rejects that condition explicitly.',
      scope: [
        'Enumerate the schema exports that define withdrawal field order in the SDK and any generated metadata.',
        'Compare them directly in one parity test instead of relying on indirect breakage.',
        'Treat any duplicate but divergent schema definition as a hard failure.',
      ],
      acceptance: [
        'Schema-order drift is caught by one targeted test.',
        'Adding a new schema export requires deliberately wiring it into the parity check.',
        'Developers do not need to infer schema conflicts from unrelated downstream test failures.',
      ],
      dependencies: ['ZK-081'],
      references: refs('sdkEncoding', 'sdkPublicInputs', 'sdkProof', 'sdkTests'),
    }),
    zkIssue({
      key: 'ZK-109',
      title: 'Lint docs, comments, and tests for stale public-input counts and nullifier semantics',
      area: 'testing',
      priority: 'Low',
      complexity: 'Medium',
      summary:
        'The repo already contains stale comments about root-bound nullifiers and mismatched public-input counts. Add a lightweight lint or audit pass so documentation drift gets caught closer to the change that introduced it.',
      scope: [
        'Identify the canonical facts that tend to drift: public-input count, field order, pool-scoped versus root-scoped nullifier semantics.',
        'Add a small lint script or focused tests that assert those facts across key docs and code comments.',
        'Keep the lint narrow enough to maintain without turning it into a documentation parser project.',
      ],
      acceptance: [
        'Known stale invariants are checked automatically.',
        'Docs and test commentary no longer contradict the current circuit contract silently.',
        'The lint output points at the specific mismatched source when it fails.',
      ],
      references: refs('readme', 'sdkEncoding', 'sdkPublicInputs', 'circuitVectors', 'wave1'),
    }),
    zkIssue({
      key: 'ZK-110',
      title: 'Track current SDK and contract ZK failures in a machine-readable triage manifest',
      area: 'testing',
      priority: 'Low',
      complexity: 'Medium',
      summary:
        'The project now has enough parallel ZK work that a free-form memory of breakage is not enough. Capture known failing suites and blockers in a machine-readable triage file until the system is green again.',
      scope: [
        'Define a compact manifest format for current ZK test and build blockers, including owner, scope, and expected exit path.',
        'Seed it with the live SDK and contract failures uncovered by current checks.',
        'Use it to drive short-lived cleanup rather than as a permanent substitute for green CI.',
      ],
      acceptance: [
        'Known ZK failures are enumerated in one machine-readable place.',
        'The manifest distinguishes dependency breakage, schema drift, and contract compile failure.',
        'The file is easy to shrink as issues are resolved and eventually removed.',
      ],
      references: refs('zkTicketCheck', 'sdkTests', 'contractIntegrationTest', 'contractUnitTest'),
    }),

    // Security, privacy, and release discipline (10)
    zkIssue({
      key: 'ZK-111',
      title: 'Add redaction helpers for notes, witnesses, proofs, and backups in logs and errors',
      area: 'security',
      priority: 'High',
      complexity: 'Medium',
      summary:
        'As proving and debugging paths become real, the SDK and tests need a single way to log structure without leaking note secrets, backup strings, or full witness payloads.',
      scope: [
        'Define redaction helpers for note material, witness fields, proof payloads, and backup strings.',
        'Use them in error paths, debug helpers, and test diagnostics that currently stringify raw structures directly.',
        'Add tests that assert sensitive substrings do not appear in redacted output.',
      ],
      acceptance: [
        'Logging helpers exist for the main ZK data types and are used consistently in debug paths.',
        'Tests prove secrets and backup strings are not emitted verbatim.',
        'Developers do not need to hand-roll ad hoc redaction in each call site.',
      ],
      references: refs('sdkNote', 'sdkProof', 'sdkWithdraw', 'sdkWitness', 'sdkTests'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-112',
      title: 'Audit fixtures and golden vectors for leaked secrets, reversible note material, and address metadata',
      area: 'security',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'The fixture corpus is growing, and it already contains realistic-looking note material and addresses. Audit what is committed so test assets do not become an accidental privacy leak or a bad example for downstream users.',
      scope: [
        'Review committed vectors, fixtures, and test snapshots for note backups, secret fields, and overly realistic address material.',
        'Replace or clearly mark any sensitive-looking fixtures that should be synthetic or redacted.',
        'Add a lightweight check for obviously unsafe fixture content.',
      ],
      acceptance: [
        'Committed ZK fixtures are reviewed under an explicit privacy standard.',
        'Unsafe or ambiguous fixture content is removed or normalized.',
        'A simple guard exists for the most obvious leakage patterns.',
      ],
      references: refs('sdkTests', 'circuitVectors', 'generateVectors'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-113',
      title: 'Verify that contract events and analytics stay aggregate-only under ZK feature growth',
      area: 'security',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'The contract already advertises privacy-preserving analytics. Revalidate that new withdraw and proof-related fields do not leak linkable metadata through events or aggregate telemetry as ZK integration deepens.',
      scope: [
        'Audit contract events and analytics storage for proof-derived, note-derived, or address-linkable values.',
        'Add tests that assert event payloads remain within the intended privacy boundary.',
        'Document what classes of ZK data are explicitly forbidden from analytics or events.',
      ],
      acceptance: [
        'Event and analytics payloads are reviewed against a written privacy boundary.',
        'Tests catch accidental addition of linkable ZK metadata.',
        'Aggregate dashboards remain consistent with the repository privacy claims.',
      ],
      references: refs('readme', 'contractEvents', 'contractAnalytics', 'contractUnitTest', 'contractIntegrationTest'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-114',
      title: 'Add malformed BN254 point and VK corpora for verifier hardening',
      area: 'security',
      priority: 'High',
      complexity: 'High',
      summary:
        'Verifier hardening needs more than length checks. Build corpora for malformed G1, G2, and VK payloads so the system can exercise non-canonical points and bad curve encodings deliberately.',
      scope: [
        'Construct malformed proof and VK examples that cover bad lengths, invalid curve points, and inconsistent IC vectors.',
        'Use the corpus in Soroban-side and SDK-side validation tests where feasible.',
        'Differentiate malformed-point rejection from simple proof-invalid rejection.',
      ],
      acceptance: [
        'Malformed-curve payloads are represented in a reusable corpus.',
        'Verifier hardening tests cover more than just short or long byte arrays.',
        'Failure categories distinguish structural corruption from cryptographic invalidity.',
      ],
      dependencies: ['ZK-075'],
      references: refs('contractVerifier', 'contractState', 'sdkProof', 'sdkTests', 'contractUnitTest'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-115',
      title: 'Add a replay matrix for cross-pool, cross-denomination, and cross-version proof reuse',
      area: 'security',
      priority: 'High',
      complexity: 'High',
      summary:
        'Nullifier and pool work is now split across circuit, SDK, and contract code. Add a replay matrix that proves the same proof or witness material cannot be replayed across pools, denominations, or artifact versions.',
      scope: [
        'Enumerate replay attempts across pool id, denomination, root history, and artifact version boundaries.',
        'Test the attempts at the cheapest layer that can reject them, and note where deeper layers also reject them.',
        'Use the matrix to validate both contract behavior and SDK-side prechecks.',
      ],
      acceptance: [
        'Replay cases are documented as a reusable matrix rather than scattered individual tests.',
        'The matrix covers cross-pool and cross-version cases, not just simple double-spend repeats.',
        'At least one cross-stack test demonstrates a failed replay at the contract boundary.',
      ],
      dependencies: ['ZK-068', 'ZK-079'],
      references: refs('sdkProof', 'sdkWithdraw', 'contractWithdraw', 'contractNullifierStorage', 'contractIntegrationTest'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-116',
      title: 'Differentiate stale-root, spent-nullifier, malformed-input, and invalid-proof failures end to end',
      area: 'security',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'Withdraw failures currently collapse too easily into generic proof failure or generic witness failure. Sharpen the error taxonomy so integrations can respond safely without leaking too much state.',
      scope: [
        'Review SDK and contract error surfaces for root expiry, spent nullifier, malformed inputs, and invalid proof outcomes.',
        'Ensure the contract emits stable error types for each class where that distinction is intentional.',
        'Mirror the same distinctions in SDK prechecks and verification helpers.',
      ],
      acceptance: [
        'Integrations can distinguish common withdraw failure classes safely.',
        'Error messages stay privacy-aware while remaining operationally useful.',
        'Tests assert the intended error mapping for representative failure cases.',
      ],
      references: refs('sdkProof', 'sdkWithdraw', 'contractErrors', 'contractWithdraw', 'contractValidation', 'contractIntegrationTest'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-117',
      title: 'Create a verifying-key rotation checklist with manifest hash and rollback checks',
      area: 'security',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'Verification-key rotation is a high-risk operational step. Add a checklist and machine checks that tie VK updates back to artifact manifests and make rollback conditions explicit.',
      scope: [
        'Define the preconditions for rotating a pool VK, including manifest hash, public-input schema, and expected contract metadata.',
        'Document or script rollback checks when a rotated VK needs to be reverted.',
        'Ensure the checklist covers multi-pool deployments rather than only one-off local updates.',
      ],
      acceptance: [
        'VK rotation has a documented and reviewable operational path.',
        'Rotation checks tie the on-chain VK update back to a concrete artifact set.',
        'Rollback conditions are explicit rather than left to operator memory.',
      ],
      dependencies: ['ZK-074'],
      references: refs('sdkArtifacts', 'contractConfigStorage', 'contractRs', 'refreshManifest'),
      labels: ['documentation'],
    }),
    zkIssue({
      key: 'ZK-118',
      title: 'Pin Node, Rust, Noir, and proving-toolchain versions in one ZK supply-chain gate',
      area: 'security',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'The repo currently checks some ZK version boundaries, but the effective proving toolchain spans more than Noir alone. Add a single gate that reports the full trusted toolchain set used for artifact generation and verification.',
      scope: [
        'Enumerate the versions that materially affect generated artifacts and proof flows across Node, Rust, Noir, and backend tooling.',
        'Add a script or CI check that captures and validates those versions together.',
        'Store the output in a form that can be tied back to artifact manifests or release bundles.',
      ],
      acceptance: [
        'The effective ZK toolchain can be inspected from one check instead of several ad hoc commands.',
        'Unexpected toolchain drift is surfaced before artifact publication.',
        'The gate is narrow enough to maintain but broad enough to cover the real trusted surface.',
      ],
      dependencies: ['ZK-064'],
      references: refs('rebuildZk', 'refreshManifest', 'sdkArtifacts', 'readme'),
    }),
    zkIssue({
      key: 'ZK-119',
      title: 'Create a release bundle that couples circuit artifacts, verifier schema, and contract metadata',
      area: 'tooling',
      priority: 'Medium',
      complexity: 'High',
      summary:
        'Versioned artifact directories are not yet the same thing as a releasable ZK bundle. Create a bundle format that carries exactly what operators and SDK consumers need for one coherent release.',
      scope: [
        'Define the contents of a ZK release bundle: circuit artifacts, proving and verification metadata, verifier schema, and contract-facing metadata.',
        'Generate the bundle from the rebuild pipeline and make it deterministic.',
        'Add validation that the bundle can be consumed by both SDK loaders and deployment tooling.',
      ],
      acceptance: [
        'One generated bundle represents a coherent ZK release instead of a loose directory of files.',
        'Bundle contents are versioned and tied back to manifest hashes.',
        'Consumers do not need to guess which subset of artifacts belongs together.',
      ],
      dependencies: ['ZK-086', 'ZK-087', 'ZK-088'],
      references: refs('sdkArtifacts', 'rebuildZk', 'refreshManifest', 'contractState'),
      labels: ['testing'],
    }),
    zkIssue({
      key: 'ZK-120',
      title: 'Add deployment preflight checks that compare target pool VK metadata against the local release bundle',
      area: 'tooling',
      priority: 'Medium',
      complexity: 'Medium',
      summary:
        'Before operators publish or rotate a verifying key, they should be able to compare the target pool state against the local ZK release bundle automatically. Add that preflight instead of relying on manual diffing.',
      scope: [
        'Read local release-bundle metadata and compare it against the target pool VK metadata and expected schema contract.',
        'Fail fast on mismatched circuit id, manifest hash, or public-input arity.',
        'Keep the preflight usable in dry-run workflows before any admin transaction is signed.',
      ],
      acceptance: [
        'Operators can run a deterministic preflight before a VK update or deployment step.',
        'Common metadata mismatches are detected before on-chain changes are attempted.',
        'The preflight is compatible with the generated release bundle and contract metadata model.',
      ],
      dependencies: ['ZK-074', 'ZK-119'],
      references: refs('sdkArtifacts', 'contractConfigStorage', 'contractState', 'issueOps', 'refreshManifest'),
      labels: ['testing', 'documentation'],
    }),
  ],
};

if (wave.issues.length !== 50) {
  throw new Error(`Expected 50 issues in zk-wave-2, found ${wave.issues.length}`);
}

export default wave;
